#!/bin/bash

EXTERNAL_FOLDER=${EXTERNAL_FOLDER:-/home/wwwroot/tinc/vpn0/public}
INTERNAL_FOLDER=${INTERNAL_FOLDER:-/home/wwwroot/tinc/vpn0}
export GEODB="${GEODB:-}"
export TINC_HOSTPATH=${TINC_HOSTPATH:-/etc/tinc/vpn0/hosts}
mapfile="$INTERNAL_FOLDER/map.html"

if test -n "$GEODB";then
    echo "creating geodata database"
    tinc-stats2json | add-geodata > "$INTERNAL_FOLDER/marker.json"
fi
build-graphs anonymous "$EXTERNAL_FOLDER"
build-graphs complete "$INTERNAL_FOLDER"
